[theme]
base = "light"
primaryColor = "#003B71"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#EEF2F7"
textColor = "#1A1A1A"
font = "sans serif"

[server]
headless = true
runOnSave = false

[browser]
gatherUsageStats = false
